# Generated by Django 4.1.5 on 2023-01-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lords',
            options={'verbose_name': 'гражданин', 'verbose_name_plural': 'граждане'},
        ),
        migrations.AlterModelOptions(
            name='soldiers',
            options={'verbose_name': 'гражданин', 'verbose_name_plural': 'граждане'},
        ),
        migrations.AddField(
            model_name='lords',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='lords',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='месячный доход'),
        ),
        migrations.AddField(
            model_name='lords',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='slaves_of_lords',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='slaves_of_lords',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='месячный доход'),
        ),
        migrations.AddField(
            model_name='slaves_of_lords',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='slaves_of_soldiers',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='slaves_of_soldiers',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='месячный доход'),
        ),
        migrations.AddField(
            model_name='slaves_of_soldiers',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='месячный доход'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
