# Generated by Django 4.1.5 on 2023-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_alter_lords_options_alter_soldiers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lords',
            options={'verbose_name': 'олигарх', 'verbose_name_plural': 'олигархи'},
        ),
        migrations.AlterModelOptions(
            name='slaves_of_lords',
            options={'verbose_name': 'пролетарий', 'verbose_name_plural': 'пролетари (для олигархов)'},
        ),
        migrations.AlterModelOptions(
            name='slaves_of_soldiers',
            options={'verbose_name': 'пролетарий', 'verbose_name_plural': 'пролетари (для солдат)'},
        ),
        migrations.AlterModelOptions(
            name='soldiers',
            options={'verbose_name': 'солдат', 'verbose_name_plural': 'солдаты'},
        ),
        migrations.AddField(
            model_name='lords',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='slaves_of_lords',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='slaves_of_soldiers',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
